Section 3: Storage Accounts
cloudquery-policies/azure-cis-1.3.0 pull request #5
Opened 2021-07-27 12:22 UTC by irmatov

2021-08-03 17:28 UTC, roneli requested changes
looks good, some changes required

2021-08-03 17:28 UTC, roneli commented on policy.hcl
> +    query "3.10" {
are you sure this is manual?  we can checking blob service logging

2021-08-03 17:28 UTC, roneli commented on policy.hcl
> +    query "3.9" {
Can this be automated?

2021-08-10 15:00 UTC, irmatov commented on policy.hcl
> +    query "3.10" {
Implemented this query

2021-08-11 06:36 UTC, irmatov commented on policy.hcl
> +    query "3.9" {
Done

2021-08-11 07:44 UTC, roneli approved these changes

2021-08-11 07:44 UTC, merged