Section 4
cloudquery-policies/azure-cis-1.3.0 pull request #7
Opened 2021-07-29 12:32 UTC by fdistorted

2021-08-03 17:22 UTC, roneli requested changes
looks good, minor check required

2021-08-03 17:22 UTC, roneli commented on policy.hcl
> +    //todo check if parameter exists
did you check it?

2021-08-04 06:57 UTC, fdistorted commented on policy.hcl
> +    //todo check if parameter exists
yes. Also I have noticed that there are redundant expect output flags in some checks. fixed them

2021-08-04 10:57 UTC, roneli approved these changes

2021-08-04 10:57 UTC, merged